### ISSUE TITLE
Problems with paths

### ISSUE THREAD

**Issue by everydayduffy** [tgrippa/Opensource_OBIA_processing_chain#1]
Hello,

Firstly, thank you very much for publishing this toolchain. I think it's a great resource that you've made available. I'm very new to python, and have in the past used OBIA tools in GRASS in bash. However, I thought I would download your notebook and try to configure it for my system. Unfortunately I've fallen at the first hurlde - setting paths!

You state that GRASS should be well installed.... For Windows users, possibly the best way to install is to use OSGEO4W. This means that the paths are quite different to the ones you provide - e.g. 

Yours:
`os.environ['GISBASE'] = 'C:\\Program Files\\GRASS GIS 7.3.svn'`

Mine:
`os.environ['GISBASE'] = 'C:\\OSGeo4W64\\apps\\grass\\grass-7.3.svn'`

This is quite a simple case that is easy to figure out. Things become a bit more difficult when locating the 'gdal' folder for example:

Yours;

`os.environ['GDAL_DATA'] = 'C:\\Program Files\\GRASS GIS 7.3.svn\\share\\gdal'`

Mine:

Doesn't exist within the share folder...

Secondly, I installed Python27 with Anaconda as you suggest, and the locations again differ to yours:

Yours:

`os.environ['PYTHONLIB'] = 'C:\\Python27'`

Mine (I think):

`os.environ['PYTHONLIB'] = 'C:\\ProgramData\\Anaconda2'`

Given that a lot of people could be using OSGEO4W and Anaconda to get GRASS and Python installed on their machines, do you think it would be possible for you to offer alternative paths given default installation options of these packages please?

Thanks again - I'm looking forward to testing some more OBIA functions on my data. I would also be happy to assist you in improving your notebook!

**Comment by tgrippa** [comment]
Hi, 

Finding the good setup for environmental variables, according to your own system could be quite tricky. 

As you are working with the OSGE4W installation, could you check if you have a folder named 'gdal' in "C:\OSGeo4W64\share". If yes, I think you could try to point to this folder for the GDAL_DATA variable, like that:
 `os.environ['GDAL_DATA'] = 'C:\\OSGeo4W64\\share\\gdal'`

Also, for the PYTHONLIB variable, I find on my system that there is a 'Python27' folder in the OSGeo4W folder. You could try to set the variable with this one :
 `os.environ['PYTHONLIB'] = 'C:\\OSGeo4W64\\apps\\Python27'`

I hope it could help. Thanks for giving feedback.

**Comment by everydayduffy** [comment]
Thanks for those recommendations, I have adjusted the paths accordingly.
