### ISSUE TITLE
Typo in importing the nDSM

### ISSUE THREAD

**Issue by MarkFizzel** [tgrippa/Opensource_OBIA_processing_chain#4]
Dear tgrippa
Firstly, great script and thank you for sharing.
I am currently running it and have noticed a small typo in the script.
In the "Import nDSM raster imagery" section, the line:
print_processing_time_a(begintime_ndsm, "nDSM imagery has been imported in ") should be:
print_processing_time(begintime_ndsm, "nDSM imagery has been imported in ")

Just FYI.

Best regards
  Mark Falkenberg

**Comment by tgrippa** [comment]
Hi @MarkFizzel, 
Thank you for the reporting. I just fixed it. 
Best
