### ISSUE TITLE
Error when importing optical raster imagery

### ISSUE THREAD

**Issue by cwyard** [tgrippa/Opensource_OBIA_processing_chain#6]
Hello,
I am using your code using Windows 10, GRASS 7.8 and Python 37.
I have this error message when I try to import raster data at the beginning of the processing chain.
Here is the complete error message :

**CalledModuleError                         Traceback (most recent call last)
<ipython-input-9-54464aa177fa> in <module>()
      8 print("Importing optical raster imagery at " + time.ctime())
      9 print("toto2")
---> 10 grass.run_command('r.in.gdal',input=r'D:\Coraline\ARCGIS\PROJETS\ZI_ORTHO_PRE-TRAITEMENTS\ZI_ORTHO_2018_READY.tif', output='optical', overwrite=True)
     11 print("toto3")
     12 for rast in grass.list_strings("rast"):

C:\OSGeo4W64\apps\grass\grass78\etc\python\grass\script\core.py in run_command(*args, **kwargs)
    439     else:
    440         returncode = ps.wait()
--> 441     return handle_errors(returncode, returncode, args, kwargs)
    442 
    443 

C:\OSGeo4W64\apps\grass\grass78\etc\python\grass\script\core.py in handle_errors(returncode, result, args, kwargs)
    341         code = ' '.join(args)
    342         raise CalledModuleError(module=None, code=code,
--> 343                                 returncode=returncode)
    344 
    345 def start_command(prog, flags="", overwrite=False, quiet=False,

CalledModuleError: Module run None r.in.gdal --o input=D:\Coraline\ARCGIS\PROJETS\ZI_ORTHO_PRE-TRAITEMENTS\ZI_ORTHO_2018_READY.tif output=optical ended with error
Process ended with non-zero return code 1. See errors in the (error) output.**

Can you help me ?

**Comment by tgrippa** [comment]
Hi @cwyard, 
Unfortunately, it is difficult to answer you without seeing the error output. What you show here is only the CalledModuleError that is displayed in your Jupyter Notebook. However, the interesting error message (the one returned by GRASS GIS) is displaying in the terminal you used to launch your jupyter notebook. 
However, I think the error here is due to the fact that you didn't double the \ in the path of your image file. Please try again usinh double \ instead of single.

**Comment by cwyard** [comment]
Hi Taïs,

Here is the error message whatever the syntax used for the path to the input file:

ERROR 1: PROJ: proj_create_from_database: Cannot find proj.db
ERROR 1: PROJ: proj_create_from_database: Cannot find proj.db
ERROR 1: PROJ: proj_create_from_database: Cannot find proj.db
ERROR 1: PROJ: proj_create_from_database: Cannot find proj.db
ERROR 1: PROJ: proj_create_from_database: Cannot find proj.db
ERROR 1: PROJ: proj_create_from_database: Cannot find proj.db
Input contains an invalid SRS. WKT definition:
LOCAL_CS["Belge_Lambert_1972",AUTHORITY["EPSG","31370"]]
ERREUR : Unable to convert input map projection information to GRASS
         format.
It is linked to the projection of the data.

I successfully imported the data manually in GRASS but I didn't work throught the Jupyter notebook :/.

I tried with another raster using the same projection. It also failed.

**Comment by tgrippa** [comment]
What command did you use to import the data manually ? If you used r.import, this module perform automatic reprojection if the data is not in the same EPSG that the one of the mapset [https://grass.osgeo.org/grass76/manuals/r.import.html]. 
What is the output of this command when you run it in the GRASS graphical interface ? : g.region -p

**Comment by cwyard** [comment]
I managed to import raster data throught the Jupyter notebook by adding flags = "o" in the command:

grass.run_command('r.in.gdal',input='D:\\Coraline\\ARCGIS\\PROJETS\\ZI_ORTHO_PRE-TRAITEMENTS\\ZI_ORTHO_2018_READY.tif', output='optical', overwrite=True, flags = 'o')

g.region -p returns this :

projection: 99 (Belge_Lambert_1972)
zone:       0
datum:      bel72
ellipsoid:  international
north:      149557.07714173
south:      144468.82714173
west:       231627.22701767
east:       236886.47701767
nsres:      0.25
ewres:      0.25
rows:       20353
cols:       21037
cells:      428166061

Now, as I managed to import data and add it to the @PERMANENT mapset throught the notebook, when I try to import data manually in the GRASS interface, it works with r.import but not with r.in.gdal.

**Comment by tgrippa** [comment]
I think it was due to a mismatch between the EPSG of your data and the EPSG of the mapset. Since It worked now, I think we can consider the issue close. 
Thanks for reporting.

**Comment by cwyard** [comment]
Thank you for your help !
